In [132]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [133]:
data= pd.read_csv(r"C:\Users\BIT\Desktop\Education 1\Projects\MoSPI\Excel Used\cpi Group data (2).csv")

In [134]:
data.head(15)

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
0,2012,2025,February,All India,Combined,Food and Beverages,Cereals and Products,200,6.1
1,2012,2025,February,All India,Combined,Food and Beverages,Meat and Fish,222.6,2.11
2,2012,2025,February,All India,Combined,Food and Beverages,Egg,196.8,-3.01
3,2012,2025,February,All India,Combined,Food and Beverages,Fruits,196.8,14.82
4,2012,2025,February,All India,Combined,Food and Beverages,Vegetables,193.4,-1.07
5,2012,2025,February,All India,Combined,Food and Beverages,Pulses and Products,201.9,-0.35
6,2012,2025,February,All India,Combined,Food and Beverages,Spices,223.9,-5.85
7,2012,2025,February,All India,Combined,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",207.7,4.16
8,2012,2025,February,All India,Combined,Food and Beverages,Non-alcoholic Beverages,183.7,3.73
9,2012,2025,February,All India,Combined,Food and Beverages,*,197.6,3.84
10,2012,2025,February,All India,Combined,"Pan, Tobacco and Intoxicants",*,210.1,2.39
11,2012,2025,February,All India,Combined,Clothing and Footwear,Clothing,196.8,2.77
12,2012,2025,February,All India,Combined,Clothing and Footwear,Footwear,186.7,2.02
13,2012,2025,February,All India,Combined,Clothing and Footwear,*,195.4,2.68
14,2012,2025,February,All India,Combined,Fuel and Light,*,178.3,-1.33

In [136]:
data[72897:72920]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
72897,2012,2021,May,Telangana,Combined,Clothing and Footwear,Footwear,152.1,2.217741935
72898,2012,2021,May,Telangana,Combined,Clothing and Footwear,*,164.3,20.27818448
72899,2012,2021,May,Telangana,Combined,Fuel and Light,*,142,-24.78813559
72900,2012,2021,May,Telangana,Combined,Miscellaneous,Household Goods and Services,144.6,3.064861012
72901,2012,2021,May,Telangana,Combined,Miscellaneous,Health,180.1,34.20268256
72902,2012,2021,May,Telangana,Combined,Miscellaneous,Transport and Communication,144.2,-6.180871828
72903,2012,2021,May,Telangana,Combined,Miscellaneous,Education,165.1,35.43888433
72904,2012,2021,May,Telangana,Combined,Miscellaneous,*,158.6,4.136572554
72905,2012,2021,May,Telangana,Rural,Food and Beverages,Cereals and Products,161.2,-4.502369668
72906,2012,2021,May,Telangana,Rural,Food and Beverages,Meat and Fish,222.3,43.41935484
72907,2012,2021,May,Telangana,Rural,Food and Beverages,Egg,175,30.49962714
72908,2012,2021,May,Telangana,Rural,Food and Beverages,Fruits,138.7,-8.929743926
72909,2012,2021,May,Telangana,Rural,Food and Beverages,Vegetables,114.2,-17.9007908
72910,2012,2021,May,Telangana,Rural,Food and Beverages,Pulses and Products,169.3,22.68115942
72911,2012,2021,May,Telangana,Rural,Food and Beverages,Spices,184.8,31.81169757
72912,2012,2021,May,Telangana,Rural,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",175.9,50.08532423
72913,2012,2021,May,Telangana,Rural,Food and Beverages,Non-alcoholic Beverages,193.3,35.55399719
72914,2012,2021,May,Telangana,Rural,Food and Beverages,*,166.7,25.24417731
72915,2012,2021,May,Telangana,Rural,"Pan, Tobacco and Intoxicants",*,200.5,26.73830594
72916,2012,2021,May,Telangana,Rural,Clothing and Footwear,Clothing,184.8,15.93475533
72917,2012,2021,May,Telangana,Rural,Clothing and Footwear,Footwear,166.6,10.40424122
72918,2012,2021,May,Telangana,Rural,Clothing and Footwear,*,182.2,13.80387258
72919,2012,2021,May,Telangana,Rural,Fuel and Light,*,140.9,-1.468531469

In [137]:
data.isnull().sum()

BaseYear         0
Year             0
Month            0
State            0
Sector           0
Group            0
SubGroup         0
Index            0
Inflation (%)    0
dtype: int64

In [138]:
data["SubGroup"].replace({"*" : np.nan}, inplace=True)

C:\Users\BIT\AppData\Local\Temp\ipykernel_16092\403528206.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["SubGroup"].replace({"*" : np.nan}, inplace=True)

In [139]:
data["Index"].replace({"*" : np.nan}, inplace=True)

C:\Users\BIT\AppData\Local\Temp\ipykernel_16092\1331821987.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Index"].replace({"*" : np.nan}, inplace=True)

In [140]:
data["Inflation (%)"].replace({"*" : np.nan}, inplace=True)

C:\Users\BIT\AppData\Local\Temp\ipykernel_16092\2710611657.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Inflation (%)"].replace({"*" : np.nan}, inplace=True)

In [141]:
data.tail(15)

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
205395,2012,2014,January,West Bengal,Urban,Food and Beverages,Pulses and Products,118,5.45
205396,2012,2014,January,West Bengal,Urban,Food and Beverages,Spices,105.9,4.23
205397,2012,2014,January,West Bengal,Urban,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",124,13.66
205398,2012,2014,January,West Bengal,Urban,Food and Beverages,Non-alcoholic Beverages,113,7.82
205399,2012,2014,January,West Bengal,Urban,Food and Beverages,NaN,121.5,11.88
205400,2012,2014,January,West Bengal,Urban,"Pan, Tobacco and Intoxicants",NaN,122.2,17.16
205401,2012,2014,January,West Bengal,Urban,Clothing and Footwear,Clothing,116.7,10.2
205402,2012,2014,January,West Bengal,Urban,Clothing and Footwear,Footwear,112,7.49
205403,2012,2014,January,West Bengal,Urban,Clothing and Footwear,NaN,116.1,9.84
205404,2012,2014,January,West Bengal,Urban,Fuel and Light,NaN,115.2,5.88
205405,2012,2014,January,West Bengal,Urban,Miscellaneous,Household Goods and Services,117.4,12.13
205406,2012,2014,January,West Bengal,Urban,Miscellaneous,Health,110.3,5.75
205407,2012,2014,January,West Bengal,Urban,Miscellaneous,Transport and Communication,111.9,5.27
205408,2012,2014,January,West Bengal,Urban,Miscellaneous,Education,111.5,6.09
205409,2012,2014,January,West Bengal,Urban,Miscellaneous,NaN,112.1,6.97

In [142]:
data[data["Index"] == "*"]

Empty DataFrame
Columns: [BaseYear, Year, Month, State, Sector, Group, SubGroup, Index, Inflation (%)]
Index: []

In [143]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205410 entries, 0 to 205409
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   BaseYear       205410 non-null  int64
 1   Year           205410 non-null  int64
 2   Month          205410 non-null  object
 3   State          205410 non-null  object
 4   Sector         205410 non-null  object
 5   Group          205410 non-null  object
 6   SubGroup       133740 non-null  object
 7   Index          204131 non-null  object
 8   Inflation (%)  204156 non-null  object
dtypes: int64(2), object(7)
memory usage: 14.1+ MB

In [144]:
data.isnull().sum()

BaseYear             0
Year                 0
Month                0
State                0
Sector               0
Group                0
SubGroup         71670
Index             1279
Inflation (%)     1254
dtype: int64

In [145]:
data.loc[data["Group"] == "Food and Beverages", "SubGroup"] = data.loc[data["Group"] == "Food and Beverages", "SubGroup"].fillna("Miscellaneous")

In [146]:
data[data["Group"] == "Food and Beverages"]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
0,2012,2025,February,All India,Combined,Food and Beverages,Cereals and Products,200,6.1
1,2012,2025,February,All India,Combined,Food and Beverages,Meat and Fish,222.6,2.11
2,2012,2025,February,All India,Combined,Food and Beverages,Egg,196.8,-3.01
3,2012,2025,February,All India,Combined,Food and Beverages,Fruits,196.8,14.82
4,2012,2025,February,All India,Combined,Food and Beverages,Vegetables,193.4,-1.07
...,...,...,...,...,...,...,...,...,...
205395,2012,2014,January,West Bengal,Urban,Food and Beverages,Pulses and Products,118,5.45
205396,2012,2014,January,West Bengal,Urban,Food and Beverages,Spices,105.9,4.23
205397,2012,2014,January,West Bengal,Urban,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",124,13.66
205398,2012,2014,January,West Bengal,Urban,Food and Beverages,Non-alcoholic Beverages,113,7.82
205399,2012,2014,January,West Bengal,Urban,Food and Beverages,Miscellaneous,121.5,11.88

In [147]:
data.head(10)

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
0,2012,2025,February,All India,Combined,Food and Beverages,Cereals and Products,200,6.1
1,2012,2025,February,All India,Combined,Food and Beverages,Meat and Fish,222.6,2.11
2,2012,2025,February,All India,Combined,Food and Beverages,Egg,196.8,-3.01
3,2012,2025,February,All India,Combined,Food and Beverages,Fruits,196.8,14.82
4,2012,2025,February,All India,Combined,Food and Beverages,Vegetables,193.4,-1.07
5,2012,2025,February,All India,Combined,Food and Beverages,Pulses and Products,201.9,-0.35
6,2012,2025,February,All India,Combined,Food and Beverages,Spices,223.9,-5.85
7,2012,2025,February,All India,Combined,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",207.7,4.16
8,2012,2025,February,All India,Combined,Food and Beverages,Non-alcoholic Beverages,183.7,3.73
9,2012,2025,February,All India,Combined,Food and Beverages,Miscellaneous,197.6,3.84

In [148]:
data.iloc[60:80]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
60,2012,2025,February,Andaman and Nicobar Islands,Combined,Food and Beverages,Miscellaneous,206.5,1.08
61,2012,2025,February,Andaman and Nicobar Islands,Combined,"Pan, Tobacco and Intoxicants",NaN,211.4,0
62,2012,2025,February,Andaman and Nicobar Islands,Combined,Clothing and Footwear,NaN,183.1,2.58
63,2012,2025,February,Andaman and Nicobar Islands,Combined,Fuel and Light,NaN,163,4.89
64,2012,2025,February,Andaman and Nicobar Islands,Combined,Miscellaneous,NaN,179.5,4.6
65,2012,2025,February,Andaman and Nicobar Islands,Rural,Food and Beverages,Miscellaneous,212.1,0.14
66,2012,2025,February,Andaman and Nicobar Islands,Rural,"Pan, Tobacco and Intoxicants",NaN,203.3,-2.68
67,2012,2025,February,Andaman and Nicobar Islands,Rural,Clothing and Footwear,NaN,197.5,3.19
68,2012,2025,February,Andaman and Nicobar Islands,Rural,Fuel and Light,NaN,158,7.19
69,2012,2025,February,Andaman and Nicobar Islands,Rural,Miscellaneous,NaN,188.8,3
70,2012,2025,February,Andaman and Nicobar Islands,Urban,Food and Beverages,Miscellaneous,198.6,2.53
71,2012,2025,February,Andaman and Nicobar Islands,Urban,"Pan, Tobacco and Intoxicants",NaN,233.7,6.96
72,2012,2025,February,Andaman and Nicobar Islands,Urban,Clothing and Footwear,NaN,165.8,1.59
73,2012,2025,February,Andaman and Nicobar Islands,Urban,Fuel and Light,NaN,170,2.1
74,2012,2025,February,Andaman and Nicobar Islands,Urban,Miscellaneous,NaN,172.3,6.03
75,2012,2025,February,Andhra Pradesh,Combined,Food and Beverages,Cereals and Products,197.8,1.12
76,2012,2025,February,Andhra Pradesh,Combined,Food and Beverages,Meat and Fish,224.2,-5.72
77,2012,2025,February,Andhra Pradesh,Combined,Food and Beverages,Egg,218.7,-6.94
78,2012,2025,February,Andhra Pradesh,Combined,Food and Beverages,Fruits,199.1,10.67
79,2012,2025,February,Andhra Pradesh,Combined,Food and Beverages,Vegetables,196.6,1.65

In [149]:
data.loc[data["Group"] == "Food and Beverages", "SubGroup"] = data.loc[data["Group"] == "Food and Beverages", "SubGroup"].replace(to_replace="Miscellaneous", value= "Residual")

In [150]:
data

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
0,2012,2025,February,All India,Combined,Food and Beverages,Cereals and Products,200,6.1
1,2012,2025,February,All India,Combined,Food and Beverages,Meat and Fish,222.6,2.11
2,2012,2025,February,All India,Combined,Food and Beverages,Egg,196.8,-3.01
3,2012,2025,February,All India,Combined,Food and Beverages,Fruits,196.8,14.82
4,2012,2025,February,All India,Combined,Food and Beverages,Vegetables,193.4,-1.07
...,...,...,...,...,...,...,...,...,...
205405,2012,2014,January,West Bengal,Urban,Miscellaneous,Household Goods and Services,117.4,12.13
205406,2012,2014,January,West Bengal,Urban,Miscellaneous,Health,110.3,5.75
205407,2012,2014,January,West Bengal,Urban,Miscellaneous,Transport and Communication,111.9,5.27
205408,2012,2014,January,West Bengal,Urban,Miscellaneous,Education,111.5,6.09
205409,2012,2014,January,West Bengal,Urban,Miscellaneous,NaN,112.1,6.97

In [151]:
data.loc[data["Group"] == "Food and Beverages"]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
0,2012,2025,February,All India,Combined,Food and Beverages,Cereals and Products,200,6.1
1,2012,2025,February,All India,Combined,Food and Beverages,Meat and Fish,222.6,2.11
2,2012,2025,February,All India,Combined,Food and Beverages,Egg,196.8,-3.01
3,2012,2025,February,All India,Combined,Food and Beverages,Fruits,196.8,14.82
4,2012,2025,February,All India,Combined,Food and Beverages,Vegetables,193.4,-1.07
...,...,...,...,...,...,...,...,...,...
205395,2012,2014,January,West Bengal,Urban,Food and Beverages,Pulses and Products,118,5.45
205396,2012,2014,January,West Bengal,Urban,Food and Beverages,Spices,105.9,4.23
205397,2012,2014,January,West Bengal,Urban,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",124,13.66
205398,2012,2014,January,West Bengal,Urban,Food and Beverages,Non-alcoholic Beverages,113,7.82
205399,2012,2014,January,West Bengal,Urban,Food and Beverages,Residual,121.5,11.88

In [152]:
data.loc[data["Group"] == "Pan, Tobacco and Intoxicants", "SubGroup"] = data.loc[data["Group"] == "Pan, Tobacco and Intoxicants", "SubGroup"].fillna("Residual")

In [153]:
data.loc[data["Group"] == "Clothing and Footwear", "SubGroup"] = data.loc[data["Group"] == "Clothing and Footwear", "SubGroup"].fillna("Residual")

In [154]:
data.loc[data["Group"] == "Fuel and Light", "SubGroup"] = data.loc[data["Group"] == "Fuel and Light", "SubGroup"].fillna("Residual")

In [155]:
data.loc[data["Group"] == "Miscellaneous", "SubGroup"] = data.loc[data["Group"] == "Miscellaneous", "SubGroup"].fillna("Residual")

In [156]:
data[60:80]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
60,2012,2025,February,Andaman and Nicobar Islands,Combined,Food and Beverages,Residual,206.5,1.08
61,2012,2025,February,Andaman and Nicobar Islands,Combined,"Pan, Tobacco and Intoxicants",Residual,211.4,0
62,2012,2025,February,Andaman and Nicobar Islands,Combined,Clothing and Footwear,Residual,183.1,2.58
63,2012,2025,February,Andaman and Nicobar Islands,Combined,Fuel and Light,Residual,163,4.89
64,2012,2025,February,Andaman and Nicobar Islands,Combined,Miscellaneous,Residual,179.5,4.6
65,2012,2025,February,Andaman and Nicobar Islands,Rural,Food and Beverages,Residual,212.1,0.14
66,2012,2025,February,Andaman and Nicobar Islands,Rural,"Pan, Tobacco and Intoxicants",Residual,203.3,-2.68
67,2012,2025,February,Andaman and Nicobar Islands,Rural,Clothing and Footwear,Residual,197.5,3.19
68,2012,2025,February,Andaman and Nicobar Islands,Rural,Fuel and Light,Residual,158,7.19
69,2012,2025,February,Andaman and Nicobar Islands,Rural,Miscellaneous,Residual,188.8,3
70,2012,2025,February,Andaman and Nicobar Islands,Urban,Food and Beverages,Residual,198.6,2.53
71,2012,2025,February,Andaman and Nicobar Islands,Urban,"Pan, Tobacco and Intoxicants",Residual,233.7,6.96
72,2012,2025,February,Andaman and Nicobar Islands,Urban,Clothing and Footwear,Residual,165.8,1.59
73,2012,2025,February,Andaman and Nicobar Islands,Urban,Fuel and Light,Residual,170,2.1
74,2012,2025,February,Andaman and Nicobar Islands,Urban,Miscellaneous,Residual,172.3,6.03
75,2012,2025,February,Andhra Pradesh,Combined,Food and Beverages,Cereals and Products,197.8,1.12
76,2012,2025,February,Andhra Pradesh,Combined,Food and Beverages,Meat and Fish,224.2,-5.72
77,2012,2025,February,Andhra Pradesh,Combined,Food and Beverages,Egg,218.7,-6.94
78,2012,2025,February,Andhra Pradesh,Combined,Food and Beverages,Fruits,199.1,10.67
79,2012,2025,February,Andhra Pradesh,Combined,Food and Beverages,Vegetables,196.6,1.65

In [161]:
data.loc[data["Index"].isna(), "Index"] = data["Index"].mode()[0]

In [175]:
# Step 1: Ensure column is numeric
data["Inflation (%)"] = pd.to_numeric(data["Inflation (%)"], errors="coerce")

# Step 2: Fill NaN values with median using loc
data.loc[data["Inflation (%)"].isna(), "Inflation (%)"] = data["Inflation (%)"].median()

In [176]:
data[203955:203975]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
203955,2012,2014,January,Arunachal Pradesh,Combined,Food and Beverages,Residual,123.4,4.89
203956,2012,2014,January,Arunachal Pradesh,Combined,"Pan, Tobacco and Intoxicants",Residual,123.4,4.89
203957,2012,2014,January,Arunachal Pradesh,Combined,Clothing and Footwear,Residual,123.4,4.89
203958,2012,2014,January,Arunachal Pradesh,Combined,Fuel and Light,Residual,123.4,4.89
203959,2012,2014,January,Arunachal Pradesh,Combined,Miscellaneous,Residual,123.4,4.89
203960,2012,2014,January,Arunachal Pradesh,Rural,Food and Beverages,Residual,114.7,7.20
203961,2012,2014,January,Arunachal Pradesh,Rural,"Pan, Tobacco and Intoxicants",Residual,112.4,5.05
203962,2012,2014,January,Arunachal Pradesh,Rural,Clothing and Footwear,Residual,122.8,14.34
203963,2012,2014,January,Arunachal Pradesh,Rural,Fuel and Light,Residual,114.6,9.35
203964,2012,2014,January,Arunachal Pradesh,Rural,Miscellaneous,Residual,111.9,6.88
203965,2012,2014,January,Arunachal Pradesh,Urban,Food and Beverages,Residual,123.4,4.89
203966,2012,2014,January,Arunachal Pradesh,Urban,"Pan, Tobacco and Intoxicants",Residual,123.4,4.89
203967,2012,2014,January,Arunachal Pradesh,Urban,Clothing and Footwear,Residual,123.4,4.89
203968,2012,2014,January,Arunachal Pradesh,Urban,Fuel and Light,Residual,123.4,4.89
203969,2012,2014,January,Arunachal Pradesh,Urban,Miscellaneous,Residual,123.4,4.89
203970,2012,2014,January,Assam,Combined,Food and Beverages,Cereals and Products,116.4,11.82
203971,2012,2014,January,Assam,Combined,Food and Beverages,Meat and Fish,112.8,10.37
203972,2012,2014,January,Assam,Combined,Food and Beverages,Egg,116.7,10.09
203973,2012,2014,January,Assam,Combined,Food and Beverages,Fruits,120.6,18.00
203974,2012,2014,January,Assam,Combined,Food and Beverages,Vegetables,122.7,18.21

In [177]:
data.to_csv("cleaned_sheet.csv")