In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel(r"C:\Users\himan\Education1\Projects\MoSPI_Updated\Data\raw\cpi_1721.xlsx")
df.head()

,base_year,series,year,month,state,sector,division,group,class,sub_class,item,code,index,inflation,imputation
0,2024,Current,2026,July,All India,Rural,Food and beverages,Food,Cereals and cereal products,NaN,NaN,01.1.1,105.48,1.65,NaN
1,2024,Current,2026,July,All India,Urban,Food and beverages,Food,Cereals and cereal products,NaN,NaN,01.1.1,105.43,1.74,NaN
2,2024,Current,2026,July,All India,Combined,Food and beverages,Food,Cereals and cereal products,NaN,NaN,01.1.1,105.46,1.68,NaN
3,2024,Current,2026,July,All India,Rural,Food and beverages,Food,"Meat, fresh, chilled or frozen",NaN,NaN,01.1.2,114.48,15.38,NaN
4,2024,Current,2026,July,All India,Urban,Food and beverages,Food,"Meat, fresh, chilled or frozen",NaN,NaN,01.1.2,114.84,15.16,NaN

In [3]:
df.shape

(182533, 15)

In [4]:
df["year"].value_counts().loc[[2025,2026]]

year
2025    115284
2026     67249
Name: count, dtype: int64

In [5]:
a= df.loc[df["year"] == 2025, "class"].unique()
a

<StringArray>
[                                                    'Cereals and cereal products',
                                                  'Meat, fresh, chilled or frozen',
                                                          'Fish and other seafood',
                                             'Milk, other dairy products and eggs',
                                                                   'Oils and fats',
                                                                 'Fruits and nuts',
                       'Vegetables, tubers, plantains, cooking bananas and pulses',
                                               'Sugar, confectionery and desserts',
                                         'Ready-made food and other food products',
                                                      'Fruit and vegetable juices',
                                                   'Coffee and coffee substitutes',
                         'Tea, maté and other plant-derived products for infusion',
                                                                 'Other beverages',
                                                                    'Cocoa drinks',
                                                                           'Water',
                                                                     'Soft drinks',
                                  'Services for processing primary goods for food',
                                                             'Spirits and liquors',
                                                                            'Wine',
                                                                            'Beer',
                                                       'Other alcoholic beverages',
                                                 'Paan and other tobacco products',
                                                              'Clothing materials',
                                                                        'Garments',
                             'Other articles of clothing and clothing accessories',
 'Cleaning, ironing, dry cleaning, dyeing, repair, tailoring and hire of clothing',
                                                        'Shoes and other footwear',
                       'Actual rental payments made by tenants for main residence',
            'Security equipment and materials for dwelling maintenance and repair',
               'Services for the maintenance, repair and security of the dwelling',
                                                                    'Water supply',
                                          'Other services related to the dwelling',
                                                                     'Electricity',
                                                                             'Gas',
                                                                    'Liquid fuels',
                                                                     'Solid fuels',
                                        'Furniture, furnishings and loose carpets',
                                                              'Household textiles',
                                   'Major electric and other household appliances',
                                                      'Small household appliances',
                                     'Glassware, tableware and household utensils',
                               'Non-motorized tools and miscellaneous accessories',
                                                     'Non-durable household goods',
                                        'Domestic services and household services',
                                                                       'Medicines',
                                                                'Medical products',
                                                              'Assistive products',
                                                  'Other outpatient care services',
                                  'Inpatient curative and rehabilitative services',
                     'Diagnostic imaging services and medical laboratory services',
                                                                      'Motor cars',
                                                                     'Motorcycles',
                                                                        'Bicycles',
                          'Parts and accessories for personal transport equipment',
                           'Fuels and lubricants for personal transport equipment',
                                                  'Passenger transport by railway',
                                                     'Passenger transport by road',
                                                      'Passenger transport by air',
                                  'Passenger transport by sea and inland waterway',
                                                     'Postal and courier services',
                                                 'Telephone instrument (landline)',
                                                                  'Mobile handset',
                                                'Information processing equipment',
                                                            'Audio-visual devices',
                                                      'Unrecorded recording media',
                  'Internet access provision services and online storage services',
                                          'Telephone charges: mobile and landline',
                                    'Other information and communication services',
              'Photographic and cinematographic equipment and optical instruments',
                                          'Games, toys and hobby-related articles',
                             'Sporting, camping and open-air recreation equipment',
                                             'Garden products, plants and flowers',
                                                           'Pets and pet products',
                                              'Recreational and sporting services',
                                                             'Musical instruments',
                       'Services provided by cinemas, theatres and concert venues',
                                                           'Photographic services',
                                                                           'Books',
                                                      'Newspapers and periodicals',
                                                'Stationery and drawing materials',
                                           'Early childhood and primary education',
                                                             'Secondary education',
                                                                'Higher education',
                                                  'Education not defined by level',
                                                 'Restaurants, cafés and the like',
                                                          'Accommodation services',
                                                    'Appliances for personal care',
                       'Other appliances, articles and products for personal care',
                        'Hairdressing salons and personal grooming establishments',
                                                           'Jewellery and watches',
                                                   'Other personal effects n.e.c.',
                                                                  'Other services']
Length: 92, dtype: str

In [6]:
b= df.loc[df["year"] == 2025, "division"].unique()
b

<StringArray>
[                                                   'Food and beverages',
                                         'Paan, tobacco and intoxicants',
                                                 'Clothing and footwear',
                      'Housing, water, electricity, gas and other fuels',
    'Furnishings, household equipment and routine household maintenance',
                                                                'Health',
                                                             'Transport',
                                         'Information and communication',
                                         'Recreation, sport and culture',
                                                    'Education services',
                                'Restaurants and accommodation services',
 'Personal care, social protection and miscellaneous goods and services']
Length: 12, dtype: str

In [7]:

# 1. Map 'division' to the target 6 Groups
group_mapping = {
    "Food and beverages": "Food and Beverages",
    "Paan, tobacco and intoxicants": "Pan, Tobacco and Intoxicants",
    "Clothing and footwear": "Clothing and Footwear",
    "Housing, water, electricity, gas and other fuels": "Housing",
    "Furnishings, household equipment and routine household maintenance": "Miscellaneous",
    "Health": "Miscellaneous",
    "Transport": "Miscellaneous",
    "Information and communication": "Miscellaneous",
    "Recreation, sport and culture": "Miscellaneous",
    "Education services": "Miscellaneous",
    "Restaurants and accommodation services": "Miscellaneous",
    "Personal care, social protection and miscellaneous goods and services": "Miscellaneous",
}

# 2. Map 'class' to the target 17 Subgroups
subgroup_mapping = {
    "Cereals and cereal products": "Cereals and Products",
    "Meat, fresh, chilled or frozen": "Meat and Fish",
    "Fish and other seafood": "Meat and Fish",
    "Milk, other dairy products and eggs": "Egg",
    "Fruits and nuts": "Fruits",
    "Vegetables, tubers, plantains, cooking bananas and pulses": "Vegetables",
    "Sugar, confectionery and desserts": "Prepared Meals, Snacks, Sweets etc.",
    "Ready-made food and other food products": "Prepared Meals, Snacks, Sweets etc.",
    "Restaurants, cafés and the like": "Prepared Meals, Snacks, Sweets etc.",
    "Fruit and vegetable juices": "Non-alcoholic Beverages",
    "Coffee and coffee substitutes": "Non-alcoholic Beverages",
    "Tea, maté and other plant-derived products for infusion": "Non-alcoholic Beverages",
    "Other beverages": "Non-alcoholic Beverages",
    "Cocoa drinks": "Non-alcoholic Beverages",
    "Water": "Non-alcoholic Beverages",
    "Soft drinks": "Non-alcoholic Beverages",
    "Clothing materials": "Clothing",
    "Garments": "Clothing",
    "Other articles of clothing and clothing accessories": "Clothing",
    "Cleaning, ironing, dry cleaning, dyeing, repair, tailoring and hire of clothing": "Clothing",
    "Shoes and other footwear": "Footwear",
    "Actual rental payments made by tenants for main residence": "Housing",
    "Security equipment and materials for dwelling maintenance and repair": "Housing",
    "Services for the maintenance, repair and security of the dwelling": "Housing",
    "Water supply": "Housing",
    "Other services related to the dwelling": "Housing",
    "Furniture, furnishings and loose carpets": "Household Goods and Services",
    "Household textiles": "Household Goods and Services",
    "Major electric and other household appliances": "Household Goods and Services",
    "Small household appliances": "Household Goods and Services",
    "Glassware, tableware and household utensils": "Household Goods and Services",
    "Non-motorized tools and miscellaneous accessories": "Household Goods and Services",
    "Non-durable household goods": "Household Goods and Services",
    "Domestic services and household services": "Household Goods and Services",
    "Medicines": "Health",
    "Medical products": "Health",
    "Assistive products": "Health",
    "Other outpatient care services": "Health",
    "Inpatient curative and rehabilitative services": "Health",
    "Diagnostic imaging services and medical laboratory services": "Health",
    "Motor cars": "Transport and Communication",
    "Motorcycles": "Transport and Communication",
    "Bicycles": "Transport and Communication",
    "Parts and accessories for personal transport equipment": "Transport and Communication",
    "Fuels and lubricants for personal transport equipment": "Transport and Communication",
    "Passenger transport by railway": "Transport and Communication",
    "Passenger transport by road": "Transport and Communication",
    "Passenger transport by air": "Transport and Communication",
    "Passenger transport by sea and inland waterway": "Transport and Communication",
    "Postal and courier services": "Transport and Communication",
    "Telephone instrument (landline)": "Transport and Communication",
    "Mobile handset": "Transport and Communication",
    "Information processing equipment": "Transport and Communication",
    "Audio-visual devices": "Transport and Communication",
    "Unrecorded recording media": "Transport and Communication",
    "Internet access provision services and online storage services": "Transport and Communication",
    "Telephone charges: mobile and landline": "Transport and Communication",
    "Other information and communication services": "Transport and Communication",
    "Books": "Education",
    "Stationery and drawing materials": "Education",
    "Early childhood and primary education": "Education",
    "Secondary education": "Education",
    "Higher education": "Education",
    "Education not defined by level": "Education",
}

# Apply mappings (unmapped classes default to 'Residual')
df["parent_group"] = df["division"].map(group_mapping)
df["subgroup"] = df["class"].map(subgroup_mapping).fillna("Residual")

# Dimensions defining unique time-series levels
group_keys = [
    "base_year",
    "series",
    "year",
    "month",
    "state",
    "sector",
    "parent_group",
    "subgroup",
]

# Numeric columns to average
numeric_cols = [c for c in ["index", "inflation"] if c in df.columns]

# Aggregate and merge rows using the arithmetic mean
merged_df = (
    df.groupby(group_keys, as_index=False)[numeric_cols]
    .mean()
    .round({"index": 2, "inflation": 2})
)

# Export the processed dataset
output_file = "cpi_aggregated.xlsx"
merged_df.to_excel(output_file, index=False)

In [8]:
merged_df.head()

,base_year,series,year,month,state,sector,parent_group,subgroup,index,inflation
0,2024,Current,2025,April,All India,Combined,Clothing and Footwear,Clothing,103.89,NaN
1,2024,Current,2025,April,All India,Combined,Clothing and Footwear,Footwear,103.30,NaN
2,2024,Current,2025,April,All India,Combined,Food and Beverages,Cereals and Products,104.13,NaN
3,2024,Current,2025,April,All India,Combined,Food and Beverages,Egg,101.61,NaN
4,2024,Current,2025,April,All India,Combined,Food and Beverages,Fruits,112.92,NaN

In [11]:
merged_df.shape

(39710, 10)