In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
data= pd.read_csv(r"C:\Users\himan\Education1\Projects\MoSPI_CPI\Data\raw\cpi Group data_initial data.csv")

In [3]:
data.head(25)

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
0,2012,2024,December,All India,Combined,Food and Beverages,Cereals and Products,198.1,6.51
1,2012,2024,December,All India,Combined,Food and Beverages,Meat and Fish,222.5,5.3
2,2012,2024,December,All India,Combined,Food and Beverages,Egg,212.1,6.85
3,2012,2024,December,All India,Combined,Food and Beverages,Fruits,190.6,8.6
4,2012,2024,December,All India,Combined,Food and Beverages,Vegetables,258.3,26.56
5,2012,2024,December,All India,Combined,Food and Beverages,Pulses and Products,214.1,3.83
6,2012,2024,December,All India,Combined,Food and Beverages,Spices,227.4,-7.41
7,2012,2024,December,All India,Combined,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",206.1,4.04
8,2012,2024,December,All India,Combined,Food and Beverages,Non-alcoholic Beverages,182,3
9,2012,2024,December,All India,Combined,Food and Beverages,*,205.9,7.69
10,2012,2024,December,All India,Combined,"Pan, Tobacco and Intoxicants",*,209.6,2.49
11,2012,2024,December,All India,Combined,Clothing and Footwear,Clothing,196.3,2.83
12,2012,2024,December,All India,Combined,Clothing and Footwear,Footwear,186.2,2.08
13,2012,2024,December,All India,Combined,Clothing and Footwear,*,194.8,2.74
14,2012,2024,December,All India,Combined,Housing,*,181.7,2.71
15,2012,2024,December,All India,Combined,Fuel and Light,*,177.8,-1.33
16,2012,2024,December,All India,Combined,Miscellaneous,Household Goods and Services,182.9,2.81
17,2012,2024,December,All India,Combined,Miscellaneous,Health,198,4.05
18,2012,2024,December,All India,Combined,Miscellaneous,Transport and Communication,171,2.64
19,2012,2024,December,All India,Combined,Miscellaneous,Education,189.7,3.95
20,2012,2024,December,All India,Combined,Miscellaneous,*,186.5,4.19
21,2012,2024,December,All India,Rural,Food and Beverages,Cereals and Products,198.9,6.82
22,2012,2024,December,All India,Rural,Food and Beverages,Meat and Fish,219.1,5.34
23,2012,2024,December,All India,Rural,Food and Beverages,Egg,209.8,6.44
24,2012,2024,December,All India,Rural,Food and Beverages,Fruits,189,9.5

In [4]:
data.info

<bound method DataFrame.info of         BaseYear  Year     Month        State    Sector               Group  \
0           2012  2024  December    All India  Combined  Food and Beverages
1           2012  2024  December    All India  Combined  Food and Beverages
2           2012  2024  December    All India  Combined  Food and Beverages
3           2012  2024  December    All India  Combined  Food and Beverages
4           2012  2024  December    All India  Combined  Food and Beverages
...          ...   ...       ...          ...       ...                 ...
215956      2012  2014   January  West Bengal     Urban       Miscellaneous
215957      2012  2014   January  West Bengal     Urban       Miscellaneous
215958      2012  2014   January  West Bengal     Urban       Miscellaneous
215959      2012  2014   January  West Bengal     Urban       Miscellaneous
215960      2012  2014   January  West Bengal     Urban       Miscellaneous

                            SubGroup  Index Inflation (%)
0               Cereals and Products  198.1          6.51
1                      Meat and Fish  222.5           5.3
2                                Egg  212.1          6.85
3                             Fruits  190.6           8.6
4                         Vegetables  258.3         26.56
...                              ...    ...           ...
215956  Household Goods and Services  117.4         12.13
215957                        Health  110.3          5.75
215958   Transport and Communication  111.9          5.27
215959                     Education  111.5          6.09
215960                             *  112.1          6.97

[215961 rows x 9 columns]>

In [5]:
data.isnull().sum()

BaseYear         0
Year             0
Month            0
State            0
Sector           0
Group            0
SubGroup         0
Index            0
Inflation (%)    0
dtype: int64

In [6]:
data["SubGroup"].replace({"*" : np.nan}, inplace=True)

C:\Users\himan\AppData\Local\Temp\ipykernel_22844\403528206.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["SubGroup"].replace({"*" : np.nan}, inplace=True)

0                 Cereals and Products
1                        Meat and Fish
2                                  Egg
3                               Fruits
4                           Vegetables
                      ...
215956    Household Goods and Services
215957                          Health
215958     Transport and Communication
215959                       Education
215960                             NaN
Name: SubGroup, Length: 215961, dtype: str

In [7]:
data["Index"].replace({"*" : np.nan}, inplace=True)

C:\Users\himan\AppData\Local\Temp\ipykernel_22844\1331821987.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["Index"].replace({"*" : np.nan}, inplace=True)

0         198.1
1         222.5
2         212.1
3         190.6
4         258.3
          ...
215956    117.4
215957    110.3
215958    111.9
215959    111.5
215960    112.1
Name: Index, Length: 215961, dtype: str

In [8]:
data["Inflation (%)"].replace({"*" : np.nan}, inplace=True)

C:\Users\himan\AppData\Local\Temp\ipykernel_22844\2710611657.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["Inflation (%)"].replace({"*" : np.nan}, inplace=True)

0          6.51
1           5.3
2          6.85
3           8.6
4         26.56
          ...
215956    12.13
215957     5.75
215958     5.27
215959     6.09
215960     6.97
Name: Inflation (%), Length: 215961, dtype: str

In [9]:
data.tail(15)

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
215946,2012,2014,January,West Bengal,Urban,Food and Beverages,Spices,105.9,4.23
215947,2012,2014,January,West Bengal,Urban,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",124,13.66
215948,2012,2014,January,West Bengal,Urban,Food and Beverages,Non-alcoholic Beverages,113,7.82
215949,2012,2014,January,West Bengal,Urban,Food and Beverages,*,121.5,11.88
215950,2012,2014,January,West Bengal,Urban,"Pan, Tobacco and Intoxicants",*,122.2,17.16
215951,2012,2014,January,West Bengal,Urban,Clothing and Footwear,Clothing,116.7,10.2
215952,2012,2014,January,West Bengal,Urban,Clothing and Footwear,Footwear,112,7.49
215953,2012,2014,January,West Bengal,Urban,Clothing and Footwear,*,116.1,9.84
215954,2012,2014,January,West Bengal,Urban,Housing,*,109.2,8.33
215955,2012,2014,January,West Bengal,Urban,Fuel and Light,*,115.2,5.88
215956,2012,2014,January,West Bengal,Urban,Miscellaneous,Household Goods and Services,117.4,12.13
215957,2012,2014,January,West Bengal,Urban,Miscellaneous,Health,110.3,5.75
215958,2012,2014,January,West Bengal,Urban,Miscellaneous,Transport and Communication,111.9,5.27
215959,2012,2014,January,West Bengal,Urban,Miscellaneous,Education,111.5,6.09
215960,2012,2014,January,West Bengal,Urban,Miscellaneous,*,112.1,6.97

In [10]:
data[data["Index"] == "*"]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
35,2012,2024,December,All India,Rural,Housing,*,*,*
66,2012,2024,December,Andaman and Nicobar Islands,Combined,Housing,*,*,*
72,2012,2024,December,Andaman and Nicobar Islands,Rural,Housing,*,*,*
95,2012,2024,December,Andhra Pradesh,Combined,Housing,*,*,*
116,2012,2024,December,Andhra Pradesh,Rural,Housing,*,*,*
...,...,...,...,...,...,...,...,...,...
215807,2012,2014,January,Uttarakhand,Rural,Housing,*,*,*
215849,2012,2014,January,Uttar Pradesh,Combined,Housing,*,*,*
215870,2012,2014,January,Uttar Pradesh,Rural,Housing,*,*,*
215912,2012,2014,January,West Bengal,Combined,Housing,*,*,*
215933,2012,2014,January,West Bengal,Rural,Housing,*,*,*

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 215961 entries, 0 to 215960
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   BaseYear       215961 non-null  int64
 1   Year           215961 non-null  int64
 2   Month          215961 non-null  str
 3   State          215961 non-null  str
 4   Sector         215961 non-null  str
 5   Group          215961 non-null  str
 6   SubGroup       215961 non-null  str
 7   Index          215961 non-null  str
 8   Inflation (%)  215961 non-null  str
dtypes: int64(2), str(7)
memory usage: 14.8 MB

In [12]:
data.isnull().sum()

BaseYear         0
Year             0
Month            0
State            0
Sector           0
Group            0
SubGroup         0
Index            0
Inflation (%)    0
dtype: int64

In [13]:
data.loc[data["Group"] == "Food and Beverages", "SubGroup"] = data.loc[data["Group"] == "Food and Beverages", "SubGroup"].fillna("Miscellaneous")

In [14]:
data[data["Group"] == "Food and Beverages"]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
0,2012,2024,December,All India,Combined,Food and Beverages,Cereals and Products,198.1,6.51
1,2012,2024,December,All India,Combined,Food and Beverages,Meat and Fish,222.5,5.3
2,2012,2024,December,All India,Combined,Food and Beverages,Egg,212.1,6.85
3,2012,2024,December,All India,Combined,Food and Beverages,Fruits,190.6,8.6
4,2012,2024,December,All India,Combined,Food and Beverages,Vegetables,258.3,26.56
...,...,...,...,...,...,...,...,...,...
215945,2012,2014,January,West Bengal,Urban,Food and Beverages,Pulses and Products,118,5.45
215946,2012,2014,January,West Bengal,Urban,Food and Beverages,Spices,105.9,4.23
215947,2012,2014,January,West Bengal,Urban,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",124,13.66
215948,2012,2014,January,West Bengal,Urban,Food and Beverages,Non-alcoholic Beverages,113,7.82
215949,2012,2014,January,West Bengal,Urban,Food and Beverages,*,121.5,11.88

In [15]:
data.head(10)

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
0,2012,2024,December,All India,Combined,Food and Beverages,Cereals and Products,198.1,6.51
1,2012,2024,December,All India,Combined,Food and Beverages,Meat and Fish,222.5,5.3
2,2012,2024,December,All India,Combined,Food and Beverages,Egg,212.1,6.85
3,2012,2024,December,All India,Combined,Food and Beverages,Fruits,190.6,8.6
4,2012,2024,December,All India,Combined,Food and Beverages,Vegetables,258.3,26.56
5,2012,2024,December,All India,Combined,Food and Beverages,Pulses and Products,214.1,3.83
6,2012,2024,December,All India,Combined,Food and Beverages,Spices,227.4,-7.41
7,2012,2024,December,All India,Combined,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",206.1,4.04
8,2012,2024,December,All India,Combined,Food and Beverages,Non-alcoholic Beverages,182,3
9,2012,2024,December,All India,Combined,Food and Beverages,*,205.9,7.69

In [16]:
data.iloc[60:80]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
60,2012,2024,December,All India,Urban,Miscellaneous,Transport and Communication,165.8,2.41
61,2012,2024,December,All India,Urban,Miscellaneous,Education,187.9,4.1
62,2012,2024,December,All India,Urban,Miscellaneous,*,182,4.12
63,2012,2024,December,Andaman and Nicobar Islands,Combined,Food and Beverages,*,216.6,3.34
64,2012,2024,December,Andaman and Nicobar Islands,Combined,"Pan, Tobacco and Intoxicants",*,213.2,2.25
65,2012,2024,December,Andaman and Nicobar Islands,Combined,Clothing and Footwear,*,180.8,1.4
66,2012,2024,December,Andaman and Nicobar Islands,Combined,Housing,*,*,*
67,2012,2024,December,Andaman and Nicobar Islands,Combined,Fuel and Light,*,163,4.89
68,2012,2024,December,Andaman and Nicobar Islands,Combined,Miscellaneous,*,183.1,4.51
69,2012,2024,December,Andaman and Nicobar Islands,Rural,Food and Beverages,*,225,3.69
70,2012,2024,December,Andaman and Nicobar Islands,Rural,"Pan, Tobacco and Intoxicants",*,205.9,0.54
71,2012,2024,December,Andaman and Nicobar Islands,Rural,Clothing and Footwear,*,193.3,1.05
72,2012,2024,December,Andaman and Nicobar Islands,Rural,Housing,*,*,*
73,2012,2024,December,Andaman and Nicobar Islands,Rural,Fuel and Light,*,158,7.19
74,2012,2024,December,Andaman and Nicobar Islands,Rural,Miscellaneous,*,188.1,2.96
75,2012,2024,December,Andaman and Nicobar Islands,Urban,Food and Beverages,*,204.6,2.81
76,2012,2024,December,Andaman and Nicobar Islands,Urban,"Pan, Tobacco and Intoxicants",*,233.3,6.72
77,2012,2024,December,Andaman and Nicobar Islands,Urban,Clothing and Footwear,*,165.8,1.91
78,2012,2024,December,Andaman and Nicobar Islands,Urban,Housing,*,206,0.24
79,2012,2024,December,Andaman and Nicobar Islands,Urban,Fuel and Light,*,170,2.1

In [17]:
data.loc[data["Group"] == "Food and Beverages", "SubGroup"] = data.loc[data["Group"] == "Food and Beverages", "SubGroup"].replace(to_replace="Miscellaneous", value= "Residual")

In [18]:
data

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
0,2012,2024,December,All India,Combined,Food and Beverages,Cereals and Products,198.1,6.51
1,2012,2024,December,All India,Combined,Food and Beverages,Meat and Fish,222.5,5.3
2,2012,2024,December,All India,Combined,Food and Beverages,Egg,212.1,6.85
3,2012,2024,December,All India,Combined,Food and Beverages,Fruits,190.6,8.6
4,2012,2024,December,All India,Combined,Food and Beverages,Vegetables,258.3,26.56
...,...,...,...,...,...,...,...,...,...
215956,2012,2014,January,West Bengal,Urban,Miscellaneous,Household Goods and Services,117.4,12.13
215957,2012,2014,January,West Bengal,Urban,Miscellaneous,Health,110.3,5.75
215958,2012,2014,January,West Bengal,Urban,Miscellaneous,Transport and Communication,111.9,5.27
215959,2012,2014,January,West Bengal,Urban,Miscellaneous,Education,111.5,6.09
215960,2012,2014,January,West Bengal,Urban,Miscellaneous,*,112.1,6.97

In [19]:
data.loc[data["Group"] == "Food and Beverages"]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
0,2012,2024,December,All India,Combined,Food and Beverages,Cereals and Products,198.1,6.51
1,2012,2024,December,All India,Combined,Food and Beverages,Meat and Fish,222.5,5.3
2,2012,2024,December,All India,Combined,Food and Beverages,Egg,212.1,6.85
3,2012,2024,December,All India,Combined,Food and Beverages,Fruits,190.6,8.6
4,2012,2024,December,All India,Combined,Food and Beverages,Vegetables,258.3,26.56
...,...,...,...,...,...,...,...,...,...
215945,2012,2014,January,West Bengal,Urban,Food and Beverages,Pulses and Products,118,5.45
215946,2012,2014,January,West Bengal,Urban,Food and Beverages,Spices,105.9,4.23
215947,2012,2014,January,West Bengal,Urban,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",124,13.66
215948,2012,2014,January,West Bengal,Urban,Food and Beverages,Non-alcoholic Beverages,113,7.82
215949,2012,2014,January,West Bengal,Urban,Food and Beverages,*,121.5,11.88

In [20]:
data.loc[data["Group"] == "Pan, Tobacco and Intoxicants", "SubGroup"] = data.loc[data["Group"] == "Pan, Tobacco and Intoxicants", "SubGroup"].fillna("Residual")

In [21]:
data["Group"].unique()

<StringArray>
[          'Food and Beverages', 'Pan, Tobacco and Intoxicants',
        'Clothing and Footwear',                      'Housing',
               'Fuel and Light',                'Miscellaneous']
Length: 6, dtype: str

In [22]:
data.loc[data["Group"] == "Clothing and Footwear", "SubGroup"] = data.loc[data["Group"] == "Clothing and Footwear", "SubGroup"].fillna("Residual")

In [23]:
data.loc[data["Group"] == "Fuel and Light", "SubGroup"] = data.loc[data["Group"] == "Fuel and Light", "SubGroup"].fillna("Residual")

In [24]:
data.loc[data["Group"] == "Miscellaneous", "SubGroup"] = data.loc[data["Group"] == "Miscellaneous", "SubGroup"].fillna("Residual")

In [25]:
data.loc[data["Group"] == "Housing", "SubGroup"] = data.loc[data["Group"] == "Housing", "SubGroup"].fillna("Housing")

In [26]:
data[60:80]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
60,2012,2024,December,All India,Urban,Miscellaneous,Transport and Communication,165.8,2.41
61,2012,2024,December,All India,Urban,Miscellaneous,Education,187.9,4.1
62,2012,2024,December,All India,Urban,Miscellaneous,*,182,4.12
63,2012,2024,December,Andaman and Nicobar Islands,Combined,Food and Beverages,*,216.6,3.34
64,2012,2024,December,Andaman and Nicobar Islands,Combined,"Pan, Tobacco and Intoxicants",*,213.2,2.25
65,2012,2024,December,Andaman and Nicobar Islands,Combined,Clothing and Footwear,*,180.8,1.4
66,2012,2024,December,Andaman and Nicobar Islands,Combined,Housing,*,*,*
67,2012,2024,December,Andaman and Nicobar Islands,Combined,Fuel and Light,*,163,4.89
68,2012,2024,December,Andaman and Nicobar Islands,Combined,Miscellaneous,*,183.1,4.51
69,2012,2024,December,Andaman and Nicobar Islands,Rural,Food and Beverages,*,225,3.69
70,2012,2024,December,Andaman and Nicobar Islands,Rural,"Pan, Tobacco and Intoxicants",*,205.9,0.54
71,2012,2024,December,Andaman and Nicobar Islands,Rural,Clothing and Footwear,*,193.3,1.05
72,2012,2024,December,Andaman and Nicobar Islands,Rural,Housing,*,*,*
73,2012,2024,December,Andaman and Nicobar Islands,Rural,Fuel and Light,*,158,7.19
74,2012,2024,December,Andaman and Nicobar Islands,Rural,Miscellaneous,*,188.1,2.96
75,2012,2024,December,Andaman and Nicobar Islands,Urban,Food and Beverages,*,204.6,2.81
76,2012,2024,December,Andaman and Nicobar Islands,Urban,"Pan, Tobacco and Intoxicants",*,233.3,6.72
77,2012,2024,December,Andaman and Nicobar Islands,Urban,Clothing and Footwear,*,165.8,1.91
78,2012,2024,December,Andaman and Nicobar Islands,Urban,Housing,*,206,0.24
79,2012,2024,December,Andaman and Nicobar Islands,Urban,Fuel and Light,*,170,2.1

In [27]:
# Convert Index_i to numeric
data["Index"] = pd.to_numeric(data["Index"], errors="coerce")

In [28]:
data.loc[data["Index"].isna(), "Index"] = data["Index"].mode()[0]

In [29]:
# Step 1: Ensure column is numeric
data["Inflation (%)"] = pd.to_numeric(data["Inflation (%)"], errors="coerce")

# Step 2: Fill NaN values with median using loc
data.loc[data["Inflation (%)"].isna(), "Inflation (%)"] = data["Inflation (%)"].median()

In [30]:
data[203955:203975]

,BaseYear,Year,Month,State,Sector,Group,SubGroup,Index,Inflation (%)
203955,2012,2014,August,Uttar Pradesh,Combined,Food and Beverages,Spices,119.4,10.35
203956,2012,2014,August,Uttar Pradesh,Combined,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",120.8,7.57
203957,2012,2014,August,Uttar Pradesh,Combined,Food and Beverages,Non-alcoholic Beverages,113.9,3.83
203958,2012,2014,August,Uttar Pradesh,Combined,Food and Beverages,*,127.8,9.79
203959,2012,2014,August,Uttar Pradesh,Combined,"Pan, Tobacco and Intoxicants",*,119.2,8.17
203960,2012,2014,August,Uttar Pradesh,Combined,Clothing and Footwear,Clothing,120.9,8.14
203961,2012,2014,August,Uttar Pradesh,Combined,Clothing and Footwear,Footwear,118.4,6.96
203962,2012,2014,August,Uttar Pradesh,Combined,Clothing and Footwear,*,120.5,7.97
203963,2012,2014,August,Uttar Pradesh,Combined,Housing,*,123.4,4.89
203964,2012,2014,August,Uttar Pradesh,Combined,Fuel and Light,*,114.1,3.35
203965,2012,2014,August,Uttar Pradesh,Combined,Miscellaneous,Household Goods and Services,115.9,6.33
203966,2012,2014,August,Uttar Pradesh,Combined,Miscellaneous,Health,113.2,5.60
203967,2012,2014,August,Uttar Pradesh,Combined,Miscellaneous,Transport and Communication,113.8,3.83
203968,2012,2014,August,Uttar Pradesh,Combined,Miscellaneous,Education,115.2,5.88
203969,2012,2014,August,Uttar Pradesh,Combined,Miscellaneous,*,113.3,5.00
203970,2012,2014,August,Uttar Pradesh,Rural,Food and Beverages,Cereals and Products,122.5,6.99
203971,2012,2014,August,Uttar Pradesh,Rural,Food and Beverages,Meat and Fish,127.0,10.05
203972,2012,2014,August,Uttar Pradesh,Rural,Food and Beverages,Egg,114.7,5.81
203973,2012,2014,August,Uttar Pradesh,Rural,Food and Beverages,Fruits,126.8,16.97
203974,2012,2014,August,Uttar Pradesh,Rural,Food and Beverages,Vegetables,170.8,21.31

In [31]:
data.rename(columns={"BaseYear": "BYear"}, inplace=True)

In [32]:
data.rename(columns={"Year": "Year_i"}, inplace=True)

In [33]:
data.rename(columns={"Month": "Month_i"}, inplace=True)

In [34]:
data.rename(columns={"State": "State_i"}, inplace=True)

In [35]:
data.rename(columns={"Index": "Index_i"}, inplace=True)

In [36]:
data.rename(columns={"Inflation (%)": "Inflation"}, inplace=True)

In [37]:
data.rename(columns={"Group": "Group_i"}, inplace=True)

In [38]:
data["Index_i"] = pd.to_numeric(data["Index_i"], errors="coerce")

In [39]:
print(data["Index_i"].isna().sum())

0

In [40]:
data["Index_i"] = data["Index_i"].astype(int)
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 215961 entries, 0 to 215960
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   BYear      215961 non-null  int64
 1   Year_i     215961 non-null  int64
 2   Month_i    215961 non-null  str
 3   State_i    215961 non-null  str
 4   Sector     215961 non-null  str
 5   Group_i    215961 non-null  str
 6   SubGroup   215961 non-null  str
 7   Index_i    215961 non-null  int64
 8   Inflation  215961 non-null  float64
dtypes: float64(1), int64(3), str(5)
memory usage: 14.8 MB

In [41]:
data["Year_i"].value_counts().loc[[2024]]

Year_i
2024    20376
Name: count, dtype: int64

In [42]:
# Strip any potential whitespace and replace '*' with 'Residual'
data["SubGroup"] = data["SubGroup"].astype(str).str.strip().replace("*", "Residual")

In [43]:
print(data.loc[data["Year_i"] == 2024, "SubGroup"].unique())

<StringArray>
[               'Cereals and Products',                       'Meat and Fish',
                                 'Egg',                              'Fruits',
                          'Vegetables',                 'Pulses and Products',
                              'Spices', 'Prepared Meals, Snacks, Sweets etc.',
             'Non-alcoholic Beverages',                            'Residual',
                            'Clothing',                            'Footwear',
        'Household Goods and Services',                              'Health',
         'Transport and Communication',                           'Education']
Length: 16, dtype: str

In [44]:
data[data["Year_i"] == 2014].head(15)

,BYear,Year_i,Month_i,State_i,Sector,Group_i,SubGroup,Index_i,Inflation
195585,2012,2014,December,All India,Combined,Food and Beverages,Cereals and Products,122,3.19
195586,2012,2014,December,All India,Combined,Food and Beverages,Meat and Fish,123,5.57
195587,2012,2014,December,All India,Combined,Food and Beverages,Egg,123,0.00
195588,2012,2014,December,All India,Combined,Food and Beverages,Fruits,125,10.94
195589,2012,2014,December,All India,Combined,Food and Beverages,Vegetables,140,-3.37
195590,2012,2014,December,All India,Combined,Food and Beverages,Pulses and Products,117,8.19
195591,2012,2014,December,All India,Combined,Food and Beverages,Spices,119,7.78
195592,2012,2014,December,All India,Combined,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",126,7.41
195593,2012,2014,December,All India,Combined,Food and Beverages,Non-alcoholic Beverages,116,4.19
195594,2012,2014,December,All India,Combined,Food and Beverages,Residual,123,4.39
195595,2012,2014,December,All India,Combined,"Pan, Tobacco and Intoxicants",Residual,123,7.89
195596,2012,2014,December,All India,Combined,Clothing and Footwear,Clothing,122,6.42
195597,2012,2014,December,All India,Combined,Clothing and Footwear,Footwear,118,5.24
195598,2012,2014,December,All India,Combined,Clothing and Footwear,Residual,122,6.27
195599,2012,2014,December,All India,Combined,Housing,Residual,116,5.24

In [45]:
data.to_csv(r"C:\Users\himan\Education1\Projects\MoSPI_CPI\Data\merged\cleaned_sheet_cpi_12-24.csv")

In [46]:
import psycopg2

In [47]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 215961 entries, 0 to 215960
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   BYear      215961 non-null  int64
 1   Year_i     215961 non-null  int64
 2   Month_i    215961 non-null  str
 3   State_i    215961 non-null  str
 4   Sector     215961 non-null  str
 5   Group_i    215961 non-null  str
 6   SubGroup   215961 non-null  str
 7   Index_i    215961 non-null  int64
 8   Inflation  215961 non-null  float64
dtypes: float64(1), int64(3), str(5)
memory usage: 14.8 MB

In [48]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://postgres:Himanshu@localhost:5432/mospi")
print("SQLAlchemy connected ✅")

SQLAlchemy connected ✅

In [49]:
import psycopg2
import pandas as pd

# 1. Load DataFrame
df = pd.read_csv("cleaned_sheet.csv")
print("Worksheet loaded ✅")

# Optional: if you don't want the auto-index column from CSV, uncomment:
# df = df.loc[:, ~df.columns.str.startswith("Unnamed")]

# 2. Connect to PostgreSQL
conn = psycopg2.connect(
    host="localhost",
    database="mospi",
    user="postgres",
    password="12345",
    port="5432"
)
cur = conn.cursor()
print("Connected to PostgreSQL ✅")

# 3. Fixed table name
table_name = "inflation"

# 4. Drop the table if it exists
cur.execute(f"DROP TABLE IF EXISTS {table_name}")
conn.commit()

# 5. Map Pandas dtypes to PostgreSQL
dtype_mapping = {
    "int64": "BIGINT",
    "float64": "DOUBLE PRECISION",
    "object": "TEXT"
}

columns = []
print("\n📌 Column → PostgreSQL type mapping:")
for col, dtype in df.dtypes.items():
    pg_type = dtype_mapping.get(str(dtype), "TEXT")  # fallback: TEXT
    print(f" - {col}: {dtype}  →  {pg_type}")
    columns.append(f'"{col}" {pg_type}')

# Create table with mapped types
create_table_query = f"CREATE TABLE {table_name} ({', '.join(columns)});"
cur.execute(create_table_query)
conn.commit()
print(f"\nTable '{table_name}' created ✅")

# 6. Insert DataFrame data into PostgreSQL (row by row)
num_cols = df.shape[1]
placeholders = ', '.join(['%s'] * num_cols)

# Build column names string, then ESCAPE any literal '%' by doubling them (%%)
col_names = ', '.join([f'"{col}"' for col in df.columns])
safe_col_names = col_names.replace('%', '%%')   # <-- important: escape % in identifiers/text

insert_query = f'INSERT INTO {table_name} ({safe_col_names}) VALUES ({placeholders})'
# Debug print (uncomment if you want to inspect the final query string)
# print("DEBUG INSERT QUERY:", insert_query)

for i, row in enumerate(df.itertuples(index=False, name=None), start=1):
    # optional debug/check:
    # if len(row) != num_cols:
    #     raise RuntimeError(f"Row length {len(row)} != num_cols {num_cols} (row index {i})")

    cur.execute(insert_query, row)

conn.commit()
print("Data inserted into PostgreSQL ✅")

# 7. Verify the data
cur.execute(f"SELECT * FROM {table_name} LIMIT 5;")
rows = cur.fetchall()
print("\nSample data from table:")
for r in rows:
    print(r)

# 8. Close connection
cur.close()
conn.close()
print("\nPostgreSQL connection closed ✅")

FileNotFoundError: [Errno 2] No such file or directory: 'cleaned_sheet.csv'